name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1.179.0
      with:
        ruby-version: '3.3'
        bundler-cache: true
    - uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - uses: pre-commit/action@v3.0.1
